### PR TITLE
Add UA CLI PR

### LINKED ISSUE #62: UA should be able to be set in the CLI as an optional arg
**Is your feature request related to a problem? Please describe.**
_No response_

**Describe the solution you'd like**
I want the user to be able to set the `User Agent` from the command line as an additional optional argument.
 
**Describe alternatives you've considered**
_No response_

**Additional context**
_No response_

### PR DESCRIPTION
**Pull request by nstrydom2**
Closes #62

### CODE REVIEW

**Comment by hentai-chan** [comment]
Just FYI, changing this line this also means you lose the `--no-verbose` options etc.

```diff
- parser.add_argument('-V', '--verbose', default=True, action=argparse.BooleanOptionalAction, help="increase output verbosity")
+ parser.add_argument('-l', '--logging', default=True, action=argparse.BooleanOptionalAction, help="enable URL logging")
```

What might have happened to you (and I'm sorry I didn't notice this earlier) is that this feature is only available in version 3.9 or higher, see also the [docs](https://docs.python.org/3/library/argparse.html) for more information.

**Comment by nstrydom2** [comment]
> 
> 
> Just FYI, changing this line this also means you lose the `--no-verbose` options etc.
> 
> ```diff
> - parser.add_argument('-V', '--verbose', default=True, action=argparse.BooleanOptionalAction, help="increase output verbosity")
> + parser.add_argument('-V', '--verbose', default=True, action='store_true', help="increase output verbosity")
> ```
> 
> What might have happened to you (and I'm sorry I didn't notice this earlier) is that this feature is only available in version 3.9 or higher, see also the [docs](https://docs.python.org/3/library/argparse.html) for more information.

Right. Which is why I removed it. I had come to the same conclusion.

**Comment by hentai-chan** [comment]
That's fine. Did you test if the user can still turn off these features?

**Comment by nstrydom2** [comment]
> 
> 
> That's fine. Did you test if the user can still turn off these features?

Good catch 💯

**Comment by hentai-chan** [comment]
I suspect you might have to change the defaults to `False`, so the user has to enable them manually all over again with `--verbose`, `--logging`, and so on. Hence why I looked into an alternative solution.

**Comment by nstrydom2** [comment]
What would you do?

**Comment by hentai-chan** [comment]
Roll out your own implementation for this flag :D

**Comment by hentai-chan** [comment]
This could also work:

1. add another `--no-verbose` flag that defaults to `False` (in addition to `--verbose` which defaults to `True`
2. Then pass `(args.verbose != args.no_verbose)` (XOR) to the `progressbar` parameter

Rinse and repeat for all the other options

**Pull request merged**
