### PR TITLE
Configure OS Matrix in Workflow File

### PR DESCRIPTION
**Pull request by StefanGreve**

### CODE REVIEW

**Comment by nstrydom2** [comment]
Do they have more than that?

**Comment by nstrydom2** [comment]
Answering my own question here, but short answer is No. We can only target those 3 runners. Otherwise, we can set up our own custom runners. I have done this for testing at my work.

**Review by nstrydom2 — APPROVED** [review]
Looks good! All we wanted was a basic config change, which is what you have done here. I would like to test this library on other open source Unix distributions, however we only have those 3 runners. It's also not worth it to run our own runners, so this will do fine for now.

**Comment by StefanGreve** [comment]
In my opinion it's also not necessary to go any further than that. As we discovered in a previous conservation, the config directory is the only part of the code that contains platform-specific logic. For everything else goes: if it can run Python 3.8+, they should be fine.

**Pull request merged**
