### PR TITLE
Revamp Project

### PR DESCRIPTION
**Pull request by hentai-chan**
# Preamble

This PR is a game changer and completely breaks any backwards compatibility. I am aware that it is a little reckless to make such grave changes in one sweep, but there are how I believe many good reasons for that:

- the original code base (OCB) contained a virtual environment that inflated the size of the repository; it is considered best practice to add any virtual environments to the `.gitignore` file
- the OCB also contained a `net.py` file which defined an interface that was never used anywhere
- many dependencies could be removed by relying on `requests` and `requests_html` for handling the network side of things, while `faker` is imported to create a fake UA; downloading files can be accomplished without `wget`
- the source code is placed below a `src` directory
- `setup.py` was rewritten by using my experience from previous projects

# Code Changes

As noted above, many things changed with this major rewrite:

- the main class is still called `AnonFile`, but the import changed from `from anonfile.anonfile import AnonFile` to `from anonfile import AnonFile` which is shorter and more convenient to write for end-users
- improved exception-handling by using `authenticated` decorator which redirects all error messages to `sys.stderr`
- the methods `download_file` and `upload_file` have been shortened to `download` and `upload`, respectively
- because this library is called `anonfile` I removed *all* references to other file sharing providers following the single-responsibility pattern (supporting multiple server providers would also have make this code more complex because they all use for the most part different endpoints for their services)
- both `download` and `upload` now use the same connection session pool
- tests can be run more easily by using the `pytest` module, so that's what I used: `pytest --verbosity=2 -s --token "REDACTED"`

I also took the liberty to update the README file and added myself as a contributor in case this PR goes through :)

### CODE REVIEW

**Comment by hentai-chan** [comment]
As a side note, it would probably be a good idea to update the changelog if this PR gets accepted.

**Review by nstrydom2 — COMMENTED** [review]
This is great, thank you. I have little experience setting up the proper 'setup.py' file, and this was very enlightening. However, there is some projects that are dependent on this one. This merge breaks backwards compatibility. Ideas?

**Comment by hentai-chan** [comment]
In my opinion breaking backwards compatibility is fair game in this case because the previous version (v0.1.3) made it clear that this library can still be prone to major changes. I can write a guide in the changelog to help users transition to the new version tomorrow. I'd also recommend using GitHub Action to make deployment of new versions to PyPI easier. Reach me by mail if you need any assistance with that.

**Comment by nstrydom2** [comment]
If you wouldn't mind writing a guide in the changelog, that would be greatly appreciated. I will look into the GitHub Action for PyPI deployment. Thanks!

**Comment by hentai-chan** [comment]
@nstrydom2 Take a look at the new changelog and let me know if there's anything that I have missed.

**Review by nstrydom2 — APPROVED** [review]
Awesome! This is some really good work. I didn't even know about the faker library. Very cool. As for the clumsy parts of the project, I was honestly being very lazy. I knew I should frag the virtual environment and update the .gitignore file. Overall, I learned a lot from your changes, and I would never have considered merging such a drastic PR if I wasn't so impressed with your work. Thanks for you contributions!

**Pull request merged**
